#eureka client配置
eureka.client.serviceUrl.defaultZone: http://admin:prolog00212@192.168.1.52:8761/eureka/

prolog.tx.url: http://192.168.0.52:7000/tx/manager/

prolog:
  serivce:
    inventory: upcloud-base-inventory-mysql
    route: service-ai-eis-route-center
  serarch:
    url: http://service-data-api-base-ai/search

spring:
  application.name: service-ai-eis-business-center
  #redis配置
  redis:
    host: 192.168.1.52
    port: 6379
    password: prolog0212
    database: 0
  #链路跟踪
  zipkin:
    sender.type: rabbit
    rabbitmq.queue: trace
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
  devtools:
    restart:
      enabled: true
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.13:2206/eis_base_business?characterEncoding=utf8&useSSL=false
    username: dev
    password: prolog0212-dev
    initialSize: 0 #初始化大小
    minIdle: 5 #最小空閒
    maxActive: 50 #最大連接數
    maxWait: 60000 #最大等待時間
    minEvictableIdleTimeMillis: 25200000 #最小生存時間
  rabbitmq:
    host: 192.168.1.52
    port: 5672
    username: admin
    password: prolog0212
    virtual-host: /

logging:
  config: classpath:log4j2-test.xml
  level.root: info    
