  #eureka client配置
eureka:
  instance:
    # 注册时使用ip而不是主机名
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ip-address}.${server.port}
    health-check-url-path: /actuator/health
    # 状态地址为api地址
    statusPageUrlPath: /${server.servlet.contextpath:}/apidoc.html
    leaseRenewalIntervalInSeconds: 20 #租期更新时间间隔（默认30秒）
    leaseExpirationDurationInSeconds: 60 #租期到期时间（默认90秒）


server:
  port: 30014
  servlet:
    context-path:

#springboot admin配置
management.endpoints.web.exposure.include: "*"

spring:
  profiles.active: dev

#熔断配置
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 42000

#ribbon配置
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 0

prolog:
  #api文档配置文件
  apidoc:
    title: EIS3.0
    basePackage: com.prolog.eis
    description: EIS3.0
    version: 1.0
  dao:
    dialect: mysql
    pagehelper: #pagehelper分页插件配置
      helperDialect: ${prolog.dao.dialect}
      reasonable: true
      supportMethodsArguments: true
      pageSizeZero: false
      params: count=countSql
    #公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
    mybatis:
      typeAliasesPackage: com.prolog.eis.model #mode包位置
      mapperLocations: classpath:mappers/*/*.xml
  ms:
    clientId: wms
    clientSecret: wms
    oauthServer: api-gateway/service-authorization
  web:
    multipart:  #文件上传配置
      maxFileSize: 100MB
      maxRequestSize: 100MB
    auth:
      redis:
        #      timeout: 18000
        namespace: "upcloud-base:"
      client-id: platform-admin
      client-secret: prolog0212
      permitResource: /*.html,/**/*.css,/**/*.js,/**/*.ico,/**/*.png,/**/*.gif,/**/*.jpg,/**/font/*,/v2/api-docs,/supervisionCodeXml/exportXml
